config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/investment.rb
class Investment < ApplicationRecord
    def change
        create_table :investments do |t|
            t.string :name
            t.timestamps
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @invest = Investment.all
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Reach out</h1>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Write here">
  <input type="submit">
</form>

app/views/pages/home.html.erb
<div class= "d-flex main_page">
    <div class="col-5">
        <div class="left_text">
            <h1>Alex Rinaldi</h1>
            <ul>
                <li><p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p></li>
                    <br>
                <li><p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p></li>
                    <br>
                <li><p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p></li>
            </ul>
        </div>
    </div>
    <div class="col-5">
        <div class="cards">
            <p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p>
            <p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p>
            <p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p>
            <p>Stocks, bonds, and other investments are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors are ultra-useful financial tools that allow investors</p>
        </div>
    </div>
</div>
<%= link_to "contact", contact_path, class: "reach_out" %>

app/views/shared/_navbar.html.erb
<%# <div class="navbar">
    <p class="d-flex align-items-center">hello</p>
</div> %>

<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</div>